spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  cloud:
    nacos:
      discovery:
        server-addr: 120.46.152.202:8848
  application:
    name: file-server
server:
  port: 9008